spirv-fuzz: Fix header guards in transformations/fuzzer passes
KhronosGroup/SPIRV-Tools pull request #3784
Opened 2020-09-09 06:25 UTC by antnkarp

I have corrected header guards in my transformations and fuzzer passes: I have replaced "SPIRV_TOOLS_..." with "SOURCE_FUZZ_..."

2020-09-09 07:16 UTC, stefanomil requested changes
In the existing fuzzer passes and transformations, there is also a _ at the end, like SOURCE_FUZZ_FUZZER_PASS_ADD_COMPOSITE_INSERTS_H_.

Could you change your ones to reflect this?

2020-09-09 07:27 UTC, antnkarp commented
> In the existing fuzzer passes and transformations, there is also a _ at the end, like SOURCE_FUZZ_FUZZER_PASS_ADD_COMPOSITE_INSERTS_H_.
> 
> Could you change your ones to reflect this?

Done, thanks.

2020-09-09 07:38 UTC, stefanomil approved these changes

2020-09-10 10:07 UTC, afd approved these changes
Thanks for fixing this!

2020-09-10 10:07 UTC, merged