spirv-val: Vulkan atomic storage class
KhronosGroup/SPIRV-Tools pull request #4079
Opened 2020-12-18 20:35 UTC by sfricke-samsung

`VUID-StandaloneSpirv-None-04686`

> The Pointer operand of all atomic instructions must have a Storage Class limited to Uniform, Workgroup, Image, StorageBuffer

2020-12-18 20:36 UTC, sfricke-samsung commented on source/val/validate_atomics.cpp
> +        if (spvIsVulkanEnv(_.context()->target_env)) {
Wasn't sure what WebGPU requires and the "correct" way spirv-val sorts out between enviornments

2020-12-21 23:07 UTC, sfricke-samsung commented
Marking as WIP until spec clarification is made on failing CI test in glslang

2021-01-11 04:45 UTC, sfricke-samsung commented
Internal Vulkan change 4296 approved that `PhysicalStorageBuffer` was missing form Vulkan spec and glslang was correct

2021-01-11 15:37 UTC, alan-baker requested changes

2021-01-11 15:37 UTC, alan-baker commented on test/val/val_atomics_test.cpp
> +              AnyVUID("VUID-StandaloneSpirv-None-04686"));
Can you please replicate this test for a universal environment to ensure we still disallow Function for Shader capability generally.

2021-01-14 14:41 UTC, alan-baker approved these changes

2021-01-14 14:41 UTC, merged