spirv-reduce: Allow merging unreachable blocks
KhronosGroup/SPIRV-Tools pull request #4303
Opened 2021-05-25 23:39 UTC by afd

This change allows the reducer to merge together blocks even when they
are unreachable, but keeps the restriction of reachability in place
for the optimizer.

Fixes #4302.

2021-06-09 18:55 UTC, afd commented
@alan-baker and @s-perron would you mind taking a look at this and checking whether you're OK with the boolean I've added to the block merge pass functionality to say whether unreachable blocks should be considered?

2021-06-09 19:00 UTC, alan-baker commented
This doesn't override allowing two merge blocks to be merged or anything similar does it?

2021-06-09 19:15 UTC, s-perron requested changes

2021-06-16 14:17 UTC, afd commented on source/opt/block_merge_util.cpp
> +    }
Good idea - thanks. I just opened #4323 which adds an `IsReachable` function to `IRContext`, refactoring various bits of code in the codebase that check for reachability. Would you be able to take a look at that PR? Assuming we can merge it, I'll then redo this PR accordingly.

2021-06-28 19:31 UTC, s-perron approved these changes

2021-06-28 22:05 UTC, merged