spirv-fuzz: Edit TransformationLoad structure to supporting OpLoad and OpAtomicLoad together.
KhronosGroup/SPIRV-Tools pull request #4336
Opened 2021-06-21 21:25 UTC by Mostafa-ashraf19

This RR is just to support the "TransformationLoad" new structure. 
Part of #4324.

2021-06-21 21:26 UTC, Mostafa-ashraf19 commented
@afd  ping. 

when you accept changes I will merge this branch with the main branch I worked on it. What do you think?

2021-07-14 09:34 UTC, afd requested changes
It turned out I had already suggested some changes on this but had forgotten to hit submit :)

2021-07-14 11:14 UTC, Mostafa-ashraf19 commented on source/fuzz/protobufs/spvtoolsfuzz.proto
> +  // Define the scope of execution.
Done.

2021-07-14 11:14 UTC, Mostafa-ashraf19 commented on source/fuzz/protobufs/spvtoolsfuzz.proto
> +  // Flag to check current load opCode is atomic or not, to take action for each one.
Done.

2021-07-22 17:16 UTC, closed without merging