Fix early-out for Clamp constant folding
KhronosGroup/SPIRV-Tools pull request #4461
Opened 2021-08-10 16:53 UTC by c0d1f1ed

Only the first two operands were tested for constness, missing the third
one. Since the FoldFPBinaryOp() at the end of FoldClamp1() returns null
when not both of its operands are constant, this doesn't change any
behavior, but it avoids some needless work.

Also the comment for FoldClamp2() was fixed.

2021-08-11 17:16 UTC, c0d1f1ed commented
I verified that this doesn't cause dEQP-VK regressions with SwiftShader: https://swiftshader-review.googlesource.com/c/SwiftShader/+/56208/2.

2021-08-13 11:24 UTC, dnovillo approved these changes

2021-08-16 13:52 UTC, s-perron commented
@c0d1f1ed Could we add a test for this as well?

2021-08-16 14:26 UTC, s-perron requested changes
Add a test or two please.  Otherwise this look good.

2021-08-16 14:59 UTC, c0d1f1ed commented
This change doesn't make any changes to the SPIR-V output, so I'm not sure if a test can be written for it. Note that there's already ample coverage for the functional aspects of constant folding Clamp instructions.

2021-08-16 18:11 UTC, s-perron approved these changes

2021-08-16 18:11 UTC, merged