Improve time to build dominators
KhronosGroup/SPIRV-Tools pull request #4916
Opened 2022-09-01 19:22 UTC by s-perron

Changed a couple small parts of the algorithm to reduce time to build
the dominator trees.  There should be no visible changes.

Add a depth first search algorithm that does not run a function on
backedges.  The check if an edge is a back edge is time consuming, and
pointless if the function run on it is a nop.

2022-09-01 20:05 UTC, vettoreldaniele requested changes

2022-09-01 20:05 UTC, vettoreldaniele commented on source/opt/dominator_tree.cpp
> +  std::unordered_map<uint32_t, BasicBlock*> id_to_BB_map;
This isn't used anymore.

2022-09-02 13:53 UTC, s-perron commented on source/cfa.h
> +      if (!backeges_is_nop && FindInWorkList(work_list, child->id())) {
Good call.  I did not know you can have an empty function object.  I was following the patterns in the code that already existed.  If fixed that up.  Now I just have two functions.  I also added asserts the the other functions are not empty.  I might revisit later to see if we can make other function possibly empty, and if that make a difference in compile time.

2022-09-02 13:58 UTC, vettoreldaniele commented on source/cfa.h
> +  /// when a back edge is encountered. The backedge function can empty.  The
nit: `can empty` -> `can be empty`

2022-09-02 13:58 UTC, vettoreldaniele approved these changes
LGTM except for the small typo. Thanks!

2022-09-02 16:27 UTC, merged