Support Narrow Types in BitCast Folding Rule
KhronosGroup/SPIRV-Tools pull request #4941
Opened 2022-09-21 23:41 UTC by gmitrano-unity

This change adds support for narrow types in the BitCastScalarOrVector folding rule. According to Section 2.2.1 of the SPIR-V spec, types that are narrower than 32 bits are automatically either sign extended, or zero extended depending on the type. With that guaranteed, we should be able to use the first 32-bit word of any narrow type for the folding logic without performing any special conversions.

In order to reduce code duplication, this change moves the GetU32BitValue and GetU64BitValue functions from IntConstant to ScalarConstant. Without this move, we would have needed an identical version of GetU32BitValue on FloatConstant.

2022-09-21 23:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=4941) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=4941) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Tools?pullRequest=4941) it.</sub>

2022-09-23 18:01 UTC, dneto0 requested changes
The implementation is good.

But this change should come with a unit test.
See test/opt/fold_test.cpp

2022-09-23 21:16 UTC, gmitrano-unity commented
Just pushed up some new test cases in the IntegerInstructionFoldingTest suite that cover 16-bit type casting. I handled the 16-bit floats in there too because I didn't see a clean way to integrate them into the FloatInstructionFoldingTest since it uses 32-bit C++ floats as the comparison value. I would have had to do some ugly casting to make them work there, so I figured it made more sense to treat them as integers. (Plus it also allows the 32-bit sign/zero extension logic to be tested)

2022-09-27 19:36 UTC, gmitrano-unity commented
Just added two more test cases to help get some coverage for 8-bit constants.
Please let me know if anything else is missing! 🙂

2022-10-06 02:49 UTC, dneto0 approved these changes
Thanks for the test cases and for your patience in waiting for the review.

2022-10-06 03:16 UTC, gmitrano-unity commented
> Thanks for the test cases and for your patience in waiting for the review.

No problem! Thank you for the review! 🙂

2022-10-06 14:35 UTC, merged