Only validate full layout in Vulkan environments
KhronosGroup/SPIRV-Tools pull request #4972
Opened 2022-10-25 17:45 UTC by alan-baker

Fixes #4671
Fixes https://crbug.com/oss-fuzz/43265

* Only validate full layout in a vulkan environment
  * Universal validation still checks that the right decorations are present, but the values are only considered for vulkan
* One exception is that invalid overlaps are only checked for vulkan
  * This is a pragmatic choice as SPIR-V doesn't define the size of types so the amount of universal checking would be quite limited
* Removed redundant check for GLSLShared and GLSLPacked decorations
  * Should never have been validated as part of universal validation

2022-10-27 11:08 UTC, Keenuts requested changes
Thanks for the work!

2022-10-27 11:08 UTC, Keenuts commented on test/val/val_decoration_test.cpp
> -OpDecorate %var DescriptorSet 0
why are those removed?

2022-10-27 14:02 UTC, alan-baker commented on source/val/validate_decorations.cpp
> +            } else if (spvIsVulkanEnv(vstate.context()->target_env)) {
Seems reasonable.

2022-10-28 09:56 UTC, Keenuts approved these changes

2022-10-28 09:57 UTC, Keenuts commented on test/val/val_decoration_test.cpp
> -OpDecorate %var DescriptorSet 0
nice to know, thansk!

2022-10-28 09:57 UTC, Keenuts commented on test/val/val_decoration_test.cpp
> +               OpExecutionMode %1 LocalSize 1 1 1
Thanks!

2022-10-28 15:52 UTC, merged