clean: constexpr-ify and unify anon namespace use
KhronosGroup/SPIRV-Tools pull request #4991
Opened 2022-11-16 13:08 UTC by Keenuts

Constexpr guaranteed no runtime init in addition to const semantics. Moving all opt/ to constexpr.
Moving all compile-unit statics to anonymous namespaces to uniformize the method used (anonymous namespace vs static has the same behavior here AFAIK).

Signed-off-by: Nathan Gauër <brioche@google.com>

2022-11-16 18:50 UTC, vettoreldaniele requested changes
Just some formatting. LGTM otherwise

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/eliminate_dead_input_components_pass.cpp
Remove newlines to match format of the rest. It looks like when we only have constexpr variables we don't keep newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/eliminate_dead_output_stores_pass.cpp
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/liveness.cpp
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/local_access_chain_convert_pass.cpp
> +}  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/local_single_block_elim_pass.cpp
> +}  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/mem_pass.cpp
>  }  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/pass.cpp
>  }  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/private_to_local_pass.cpp
>  }  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/reduce_load_size.cpp
>  }  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/type_manager.cpp
>  }  // namespace
Remove newlines

2022-11-16 18:50 UTC, vettoreldaniele commented on source/opt/vector_dce.cpp
>  }  // namespace
Remove newlines

2022-11-16 19:02 UTC, Keenuts commented
Thanks, went through files again, and made the anonymous namespace placement uniform (no new-line, inside other namespaces). Had missed a few.

2022-11-16 19:40 UTC, vettoreldaniele submitted a review, later dismissed

2022-11-17 17:50 UTC, vettoreldaniele approved these changes

2022-11-17 18:02 UTC, merged