README.md: The validator now handles larger limits
KhronosGroup/SPIRV-Tools pull request #5003
Opened 2022-11-27 23:32 UTC by SamB

2022-11-27 23:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=5003) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=5003) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Tools?pullRequest=5003) it.</sub>

2022-11-28 17:59 UTC, vettoreldaniele requested changes

2022-11-28 17:59 UTC, vettoreldaniele commented on README.md
> +The validator has been parameterized to allow larger values, for use when targetting
typo: `targetting` -> `targeting`

2022-12-16 02:34 UTC, dneto0 approved these changes
Thanks!

2022-12-16 02:35 UTC, merged