Fix null pointer in FoldInsertWithConstants.
KhronosGroup/SPIRV-Tools pull request #5093
Opened 2023-01-31 20:51 UTC by LukasBanana

Struct types are not supported in constant folding yet.

2023-02-01 14:00 UTC, s-perron reviewed
@LukasBanana Thanks for the fix, but could you add a test for this?

2023-02-01 14:27 UTC, LukasBanana commented
I was trying to reproduce the issue with a small test, but so far it only occurred with one of our large Niagara shaders and I can't add them to this repository.
I can point you to the null pointer, though:
https://github.com/KhronosGroup/SPIRV-Tools/blob/main/source/opt/constants.cpp#L412

2023-02-01 17:32 UTC, s-perron commented
I don't think it should be all that hard to reproduce in a folding test.

You will want to add a test to https://github.com/KhronosGroup/SPIRV-Tools/blob/0994ca45b663296d733e89c5d89dbd4347e065c1/test/opt/fold_test.cpp#L7088

The new tests will be similar to https://github.com/KhronosGroup/SPIRV-Tools/blob/0994ca45b663296d733e89c5d89dbd4347e065c1/test/opt/fold_test.cpp#L7297.

You will want to have an insert that is something like:

```
%4 = OpCompositeInsert  %struct_v2int_int_int %int_1 %struct_v2int_int_int_null 2
```

I believe that should reproduce your problem.

2023-02-02 14:08 UTC, s-perron requested changes

2023-02-02 14:08 UTC, s-perron commented on test/opt/fold_test.cpp
> +    // Test case 16: Don't fold when type cannot be deduced to a constant.
You need to add a comma in the line before this.

2023-02-02 14:08 UTC, s-perron commented on test/opt/fold_test.cpp
> +        4, false),
You should double check, but I think you need to remove this comma.

2023-02-02 15:12 UTC, LukasBanana commented
Thanks for your feedback. I don't have a proper workflow for the test cases yet, but will do that for the next PR.

2023-02-03 15:03 UTC, merged