Don't convert struct members to half
KhronosGroup/SPIRV-Tools pull request #5201
Opened 2023-04-19 11:11 UTC by cjo20

An initial (and possibly overzealous) attempt at fixing #4814 

This currently just stops conversion to half when it's reading from a struct. This could lead to cases that could be optimised being missed - that would require checking the members of the struct to determine whether they're compatible with half.

2023-04-19 11:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=5201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Tools?pullRequest=5201) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Tools?pullRequest=5201) it.</sub>

2023-04-27 21:47 UTC, greg-lunarg commented
Why should struct members not be converted to half?

2023-05-04 15:22 UTC, s-perron commented
@cjo20 Can you a new test? This will provide an example that we can use to better understand the problem. It will also fill a hole it our testing, and help avoid regressions in the future. Here is a sample test that you can use to get started:

https://github.com/KhronosGroup/SPIRV-Tools/blob/01055c60cfc0cddd2724dc674ed73d09df992360/test/opt/convert_relaxed_to_half_test.cpp#L1426

2023-05-04 19:47 UTC, cjo20 commented
I've spent some time trying to get a test working and I've not had much luck. I've tried to create a small case that reproduces the problem - the following shader in HLSL:

```
struct myStruct
{
	float f;
};

ConstantBuffer<myStruct> MyConstants : register(b2, space1);

half ExtractVal(myStruct a)
{
	return a.f;
}

float PSMain() : SV_TARGET
{
	return ExtractVal(MyConstants);
}
```

Which converts to the following SPIRV:
```
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %PSMain "PSMain" %out_var_SV_TARGET %MyConstants
               OpExecutionMode %PSMain OriginUpperLeft
               OpSource HLSL 600
               OpName %type_ConstantBuffer_myStruct "type.ConstantBuffer.myStruct"
               OpMemberName %type_ConstantBuffer_myStruct 0 "f"
               OpName %MyConstants "MyConstants"
               OpName %out_var_SV_TARGET "out.var.SV_TARGET"
               OpName %PSMain "PSMain"
               OpDecorate %out_var_SV_TARGET Location 0
               OpDecorate %MyConstants DescriptorSet 1
               OpDecorate %MyConstants Binding 2
               OpMemberDecorate %type_ConstantBuffer_myStruct 0 Offset 0
               OpDecorate %type_ConstantBuffer_myStruct Block
      %float = OpTypeFloat 32
%type_ConstantBuffer_myStruct = OpTypeStruct %float
%_ptr_Uniform_type_ConstantBuffer_myStruct = OpTypePointer Uniform %type_ConstantBuffer_myStruct
%_ptr_Output_float = OpTypePointer Output %float
       %void = OpTypeVoid
          %9 = OpTypeFunction %void
%MyConstants = OpVariable %_ptr_Uniform_type_ConstantBuffer_myStruct Uniform
%out_var_SV_TARGET = OpVariable %_ptr_Output_float Output
     %PSMain = OpFunction %void None %9
         %10 = OpLabel
         %11 = OpLoad %type_ConstantBuffer_myStruct %MyConstants
         %12 = OpCompositeExtract %float %11 0
               OpStore %out_var_SV_TARGET %12
               OpReturn
               OpFunctionEnd
```

Running with `--convert-relaxed-to-half` does reproduce the issue, as 
```        
        %12 = OpCompositeExtract %float %11 0
```
becomes
```
        %12 = OpCompositeExtract %half %11 0
        %14 = OpFConvert %float %12
```
Which then fails spirv-val with the message 
```
error: line 29: Result type (OpTypeFloat) does not match the type that results from indexing into the composite (OpTypeFloat).
  %12 = OpCompositeExtract %half %11 0
```

Running with my suggested change results in the OpCompositeExtract line not changing, and therefore not failing validation.

I've not used googletest before, and I've not got time to look in to generating the test itself right now.

2023-05-05 21:36 UTC, greg-lunarg requested changes
I am fine with this change when a test is added. Thanks for the fix!

2023-05-08 15:03 UTC, s-perron commented
I added the test. @cjo20 I should have pointed you to a different example because your test is suppose to be a "nopt".

2023-05-08 16:14 UTC, s-perron approved these changes
Greg said he was okay with it once a test was added. It has been added, so I will approve it.

2023-05-08 16:14 UTC, merged