Add Abseil as a dep and update RE2
KhronosGroup/SPIRV-Tools pull request #5236
Opened 2023-05-24 18:30 UTC by s-perron

The latest version of RE2 requires Abseil. This PR adds Abseil as an
external dependence, and update RE2 to use it.

2023-05-24 18:53 UTC, dnovillo requested changes
more dependencies!  what fun...

2023-05-24 18:53 UTC, dnovillo commented on external/CMakeLists.txt
> +      message(STATUS "STEVEN: abseil is not a valid target")
debug code leftover?

2023-05-24 18:57 UTC, s-perron commented on external/CMakeLists.txt
> +      message(STATUS "STEVEN: abseil is not a valid target")
:man_facepalming:

2023-05-24 19:27 UTC, dnovillo approved these changes

2023-05-25 13:00 UTC, merged

2023-06-13 19:11 UTC, LukasBanana commented
@s-perron @dnovillo since I'm running into build issues due to this new dependency, I was wondering why we can't simply add all these dependencies as submodules to simplify git clone process? Or am I missing something from the build documentation?

2023-06-13 19:19 UTC, dnovillo commented
@LukasBanana I sometimes wish SPIRV-Tools used submodules, but it uses the "sync deps scripts" model (https://github.com/KhronosGroup/SPIRV-Tools#getting-the-source).  I'm not actually sure why abseil is not updated that way, though.  @s-perron maybe we should fix CMake to use `abseil-cpp`?

2023-06-13 19:22 UTC, LukasBanana commented
I just noticed that _effcee_ has this CMake condition:
```
  if (IS_DIRECTORY "${EFFCEE_THIRD_PARTY_ROOT_DIR}/abseil_cpp")
    set(EFFCEE_ABSEIL_DIR "${EFFCEE_THIRD_PARTY_ROOT_DIR}/abseil_cpp" CACHE STRING "Location of abseil source")
  elseif(IS_DIRECTORY "${EFFCEE_THIRD_PARTY_ROOT_DIR}/abseil-cpp")
    set(EFFCEE_ABSEIL_DIR "${EFFCEE_THIRD_PARTY_ROOT_DIR}/abseil-cpp" CACHE STRING "Location of abseil source")
  endif()
```
But I'm not sure how that ties in with the SPIRV-Tools CMake script.