kokoro: rename glslang
KhronosGroup/SPIRV-Tools pull request #5339
Opened 2023-07-19 17:17 UTC by Keenuts

glslangValidator was renamed to glslang
(https://github.com/KhronosGroup/glslang/pull/3257). Fixing build.

2023-07-19 20:40 UTC, dneto0 commented on kokoro/scripts/linux/build-docker.sh
> +  ninja glslang
Is the Cmake target is actually glslang-standalone? 

See https://github.com/KhronosGroup/glslang/pull/3257/files

2023-07-19 21:46 UTC, dneto0 commented
I wonder why the smoketest didn't run ?  That is what is sensitive to the propblem in the first place.

2023-07-19 22:06 UTC, s-perron commented
I disabled auto merge because the smoketest should pass for this pr, but is it generally not required.

2023-07-19 22:32 UTC, dneto0 commented on kokoro/scripts/linux/build-docker.sh
> +  ninja glslang
Indeed you have to invoke "glslang-standalone" to build the executables

```
dneto@dneto1:/build/shaderc/build$ ls -l third_party/glslang/StandAlone/
total 248
drwxr-x--- 4 dneto dneto   4096 Jul 19 18:24 CMakeFiles
-rw-r----- 1 dneto dneto   3669 Jul 19 18:24 cmake_install.cmake
-rw-r----- 1 dneto dneto    347 Jul 19 18:24 CTestTestfile.cmake
-rw-r----- 1 dneto dneto    374 Jul 19 18:24 glslang-standaloneTargets.cmake
-rwxr-x--- 1 dneto dneto 232144 Jul 19 18:26 spirv-remap
-rw-r----- 1 dneto dneto    370 Jul 19 18:24 spirv-remapTargets.cmake
dneto@dneto1:/build/shaderc/build$ ninja glslang
ninja: no work to do.
dneto@dneto1:/build/shaderc/build$ ls -l third_party/glslang/StandAlone/
total 248
drwxr-x--- 4 dneto dneto   4096 Jul 19 18:24 CMakeFiles
-rw-r----- 1 dneto dneto   3669 Jul 19 18:24 cmake_install.cmake
-rw-r----- 1 dneto dneto    347 Jul 19 18:24 CTestTestfile.cmake
-rw-r----- 1 dneto dneto    374 Jul 19 18:24 glslang-standaloneTargets.cmake
-rwxr-x--- 1 dneto dneto 232144 Jul 19 18:26 spirv-remap
-rw-r----- 1 dneto dneto    370 Jul 19 18:24 spirv-remapTargets.cmake
dneto@dneto1:/build/shaderc/build$ ninja glslang-standalone
[1/1] Linking CXX executable third_party/glslang/StandAlone/glslang
dneto@dneto1:/build/shaderc/build$ ls -l third_party/glslang/StandAlone/
total 8804
drwxr-x--- 4 dneto dneto    4096 Jul 19 18:24 CMakeFiles
-rw-r----- 1 dneto dneto    3669 Jul 19 18:24 cmake_install.cmake
-rw-r----- 1 dneto dneto     347 Jul 19 18:24 CTestTestfile.cmake
-rwxr-x--- 1 dneto dneto 8760696 Jul 19 18:31 glslang
-rw-r----- 1 dneto dneto     374 Jul 19 18:24 glslang-standaloneTargets.cmake
lrwxrwxrwx 1 dneto dneto       7 Jul 19 18:31 glslangValidator -> glslang
-rwxr-x--- 1 dneto dneto  232144 Jul 19 18:26 spirv-remap
-rw-r----- 1 dneto dneto     370 Jul 19 18:24 spirv-remapTargets.cmake
```

2023-07-19 22:33 UTC, dneto0 requested changes
The ninja target is `glslang-standalone`

2023-07-20 09:08 UTC, Keenuts commented
> I disabled auto merge because the smoketest should pass for this pr, but is it generally not required.

Ahh thanks! Assumed smoketest was blocking...

2023-07-20 09:11 UTC, Keenuts commented
> The ninja target is `glslang-standalone`

Thanks! Fixed, and will check if smoketest passes before enabling auto-merge this time! 😊

2023-07-20 13:05 UTC, dneto0 approved these changes
Thanks!
I made the corresponding change in Shaderc. https://github.com/google/shaderc/pull/1354

2023-07-20 13:05 UTC, merged