spirv-val: Disallow stores according to VUID 06924
KhronosGroup/SPIRV-Tools pull request #5368
Opened 2023-08-09 15:31 UTC by svenvh

Ensure that the validator rejects stores to objects of types
`OpTypeImage`, `OpTypeSampler`, `OpTypeSampledImage`,
`OpTypeAccelerationStructureKHR`, and arrays of these types, according
to `VUID-StandaloneSpirv-OpTypeImage-06924`.

Guard the check behind the before_hlsl_legalization option, as
sometimes we may have temporaries or local variables that are expected
to get optimized away.

Fixes #4796

2023-08-09 16:26 UTC, svenvh commented
If I understand the CI failures correctly, HLSL-to-SPIR-V translation by glslang and shaderc seems to result in some violations of this VUID, as HLSL allows the construct.  Any suggestions what to do here?

2023-08-09 23:41 UTC, alan-baker commented
What does glslang do in the GLSL path when you have a local acceleration structure variable?

2023-08-10 13:16 UTC, svenvh commented
GLSL allows acceleration structures (and images/samplers) only as uniforms or function parameters, and glslang diagnoses incorrect uses:
```
ERROR: 0:10: 'accelerationStructureNV' : accelerationStructureNV can only be used in uniform variables or function parameters
```

2023-09-19 01:43 UTC, spencer-lunarg commented
Does this check cases where there is a `OpImageWrite` through an `OpLoad` or and Atomic instructions?

2023-09-25 14:57 UTC, svenvh commented
> Does this check cases where there is a `OpImageWrite` through an `OpLoad` or and Atomic instructions?

`OpImageWrite` is checked elsewhere (in `ValidateImageWrite`) as far as I can tell.

2024-04-19 13:25 UTC, svenvh commented
To progress on this, I've excluded validation of stores to objects of types `OpTypeImage` and `OpTypeSampler`.

2024-09-20 13:36 UTC, alan-baker requested changes
Just some updates to the message for now.

2024-09-20 13:36 UTC, alan-baker commented on source/val/validate_memory.cpp
> +             << "Cannot store to OpTypeImage, OpTypeSampler, "
Nit: these types are not checked currently.

2024-09-20 14:12 UTC, alan-baker commented
@s-perron Coming from a DXC perspective, should this check be gated by a pre legalization guard?

2024-09-20 14:27 UTC, s-perron commented
I'm not sure. The OpTypeImage and OpTypeSampler should be guarded. We do not currently generate OpTypeSampledImage in a way that would require it, but I think that could happen in the near future.

I would say yes it we should check the flag. In general, the compiler may add temporaries or the user may have local variables that are expect to get optimized away.

This would be to solution to the issue with OpTypeImage and OpTypeSampler mentioned above. The output from the glslang HLSL->SPIRV should be validated with the pre-legalization option. If the checks are guarded by that option, then they should pass.

2024-09-20 14:32 UTC, svenvh commented
> This would be to solution to the issue with OpTypeImage and OpTypeSampler mentioned above. The output from the glslang HLSL->SPIRV should be validated with the pre-legalization option. If the checks are guarded by that option, then they should pass.

@s-perron thanks for the suggestion, I'd much rather land the complete validation including OpTypeImage and OpTypeSampler.  Is it `options()->before_hlsl_legalization` that you're referring to?

2024-09-20 15:14 UTC, svenvh commented
I've reinstated the full checks, including OpTypeImage and OpTypeSampler, now all guarded behind before_hlsl_legalization.

2024-09-23 12:34 UTC, alan-baker approved these changes

2024-09-23 12:34 UTC, merged